version: '3'

services:
  app:
    # This approach would build new image tagged as repository on every docker compose
    # up command with latest version
    image: analytics-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: bash -c "alembic upgrade head && uvicorn app.api.main:bootstrap --host 0.0.0.0 --port 8080 --reload"
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432
