"""Add project

Revision ID: 3cdf5ba545b0
Revises: d491157f77a9
Create Date: 2023-05-23 10:57:35.798769

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3cdf5ba545b0"
down_revision = "d491157f77a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("links", sa.ARRAY(sa.String()), nullable=False))
    op.drop_constraint("project_url_key", "project", type_="unique")
    op.drop_column("project", "url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.create_unique_constraint("project_url_key", "project", ["url"])
    op.drop_column("project", "links")
    # ### end Alembic commands ###
