"""initial

Revision ID: 7b318515e90f
Revises:
Create Date: 2023-05-21 20:10:27.154499

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7b318515e90f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commit",
        sa.Column("uid", sa.INTEGER(), sa.Identity(always=False), nullable=False),
        sa.Column("project_id", sa.INTEGER(), nullable=False),
        sa.Column("author_login", sa.VARCHAR(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=False),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_table(
        "issue",
        sa.Column("uid", sa.INTEGER(), sa.Identity(always=False), nullable=False),
        sa.Column("project_id", sa.INTEGER(), nullable=False),
        sa.Column("author_login", sa.VARCHAR(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("closed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=False),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_table(
        "label",
        sa.Column("uid", sa.INTEGER(), sa.Identity(always=False), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "pull_request",
        sa.Column("uid", sa.INTEGER(), sa.Identity(always=False), nullable=False),
        sa.Column("project_id", sa.INTEGER(), nullable=False),
        sa.Column("author_login", sa.VARCHAR(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("closed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=False),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_table(
        "issue_label",
        sa.Column("uid", sa.INTEGER(), sa.Identity(always=False), nullable=False),
        sa.Column("issue_uid", sa.INTEGER(), nullable=False),
        sa.Column("label_uid", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["issue_uid"], ["issue.uid"], onupdate="RESTRICT", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["label_uid"], ["label.uid"], onupdate="RESTRICT", ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("issue_label")
    op.drop_table("pull_request")
    op.drop_table("label")
    op.drop_table("issue")
    op.drop_table("commit")
    # ### end Alembic commands ###
