"""Add project

Revision ID: d491157f77a9
Revises: 7b318515e90f
Create Date: 2023-05-23 10:18:16.335491

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d491157f77a9"
down_revision = "7b318515e90f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project",
        sa.Column("uid", sa.INTEGER(), sa.Identity(always=False), nullable=False),
        sa.Column("url", sa.VARCHAR(), nullable=False),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=False),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("url"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project")
    # ### end Alembic commands ###
